---
  reference:
    genepanels:
      checksum: ef950ee9a9ee324c0a0dbb8de662c94a
      path: poirot/config/gene_panels/genepanels_WGS.list
      type: file
      url: file:poirot_config/config/gene_panels/genepanels_WGS.list
    Amyloidos:
      path: poirot/config/gene_panels/Amyloidos.list
      checksum: 6387f9e8093d31d4abcc5feca3777180
      type: file
      url: file:poirot_config/config/gene_panels/Amyloidos.list
    Angioodem_v1:
      path: poirot/config/gene_panels/Angioodem_v1.list
      checksum: 56148127c908f5c7d12b50790680288e
      type: file
      url: file:poirot_config/config/gene_panels/Angioodem_v1.list
    Arytmi_och_kardiomyopati_v3:
      path: poirot/config/gene_panels/Arytmi_och_kardiomyopati_v3.list
      checksum: 29be7b7c6a090efdef7fbe70faa3d78e
      type: file
      url: file:poirot_config/config/gene_panels/Arytmi_och_kardiomyopati_v3.list
    Ataxi_v5:
      path: poirot/config/gene_panels/Ataxi_v5.list
      checksum: 91e54876084e75949396e52fce7e4e63
      type: file
      url: file:poirot_config/config/gene_panels/Ataxi_v5.list
    Bindvav_v3:
      path: poirot/config/gene_panels/Bindvav_v3.list
      checksum: 50fe5df592d43ee34d11b6dc169736f1
      type: file
      url: file:poirot_config/config/gene_panels/Bindvav_v3.list
    Blueprint_pseudogenes:
      path: poirot/config/gene_panels/Blueprint_pseudogenes.list
      checksum: eff138ee4eb521806c0b7d5a995b43e7
      type: file
      url: file:poirot_config/config/gene_panels/Blueprint_pseudogenes.list
    Bred_NMD_v1:
      path: poirot/config/gene_panels/Bred_NMD_v1.list
      checksum: 919286e31f1c8a60fd7a10d39b64df07
      type: file
      url: file:poirot_config/config/gene_panels/Bred_NMD_v1.list
    Bred_skelettdysplasi:
      path: poirot/config/gene_panels/Bred_skelettdysplasi.list
      checksum: e9edda1c5d9553cfe0ac51e25c9e7959
      type: file
      url: file:poirot_config/config/gene_panels/Bred_skelettdysplasi.list
    Cadasil:
      path: poirot/config/gene_panels/Cadasil.list
      checksum: de698fc0d599d9750bf31ec9af4295db
      type: file
      url: file:poirot_config/config/gene_panels/Cadasil.list
    Cerebrala_smakarlssjukdomar_v3:
      path: poirot/config/gene_panels/Cerebrala_smakarlssjukdomar_v3.list
      checksum: 9d3ed23816dd18ebd683edce3b0c72b5
      type: file
      url: file:poirot_config/config/gene_panels/Cerebrala_smakarlssjukdomar_v3.list
    ChiCaP:
      path: poirot/config/gene_panels/ChiCaP.list
      checksum: 1751c2ce331a6273c2336a0bde2f6509
      type: file
      url: file:poirot_config/config/gene_panels/ChiCaP.list
    Ciliopati_v1:
      path: poirot/config/gene_panels/Ciliopati_v1.list
      checksum: 5547a9783124b22eae5108cc60153466
      type: file
      url: file:poirot_config/config/gene_panels/Ciliopati_v1.list
    Cornealdystrofi:
      path: poirot/config/gene_panels/Cornealdystrofi.list
      checksum: 6fafb4a0852f48613c1f11e57045f30e
      type: file
      url: file:poirot_config/config/gene_panels/Cornealdystrofi.list
    DSD:
      path: poirot/config/gene_panels/DSD.list
      checksum: 2fb33685027e86840ba84863cb119441
      type: file
      url: file:poirot_config/config/gene_panels/DSD.list
    Dystoni:
      path: poirot/config/gene_panels/Dystoni.list
      checksum: d70f74921bc3777ae4c507a02cc8f7ed
      type: file
      url: file:poirot_config/config/gene_panels/Dystoni.list
    EB_v2:
      path: poirot/config/gene_panels/EB_v2.list
      checksum: ef7429ba0220021f480ab5f0d4f4ef45
      type: file
      url: file:poirot_config/config/gene_panels/EB_v2.list
    Ektodermal_dysplasi:
      path: poirot/config/gene_panels/Ektodermal_dysplasi.list
      checksum: e946edbc1c25c279d4e5fda96acc2036
      type: file
      url: file:poirot_config/config/gene_panels/Ektodermal_dysplasi.list
    Endokrin:
      path: poirot/config/gene_panels/Endokrin.list
      checksum: 125788f7519875ecda3e8f83e364257b
      type: file
      url: file:poirot_config/config/gene_panels/Endokrin.list
    Epilepsi:
      path: poirot/config/gene_panels/Epilepsi.list
      checksum: a40aa6b0a53e323f7873ae79936c791a
      type: file
      url: file:poirot_config/config/gene_panels/Epilepsi.list
    Fostermissbildningar_v1:
      path: poirot/config/gene_panels/Fostermissbildningar_v1.list
      checksum: 4d5a2cb95a54b4e58801a2e23419249c
      type: file
      url: file:poirot_config/config/gene_panels/Fostermissbildningar_v1.list
    Gitelman_Bartter_Liddle_v1:
      path: poirot/config/gene_panels/Gitelman_Bartter_Liddle_v1.list
      checksum: aca29a8b1cb0484ae0364c1952294c80
      type: file
      url: file:poirot_config/config/gene_panels/Gitelman_Bartter_Liddle_v1.list
    Hematologi:
      path: poirot/config/gene_panels/Hematologi.list
      checksum: f299e39c35aab6ba2700e96a6c713bdc
      type: file
      url: file:poirot_config/config/gene_panels/Hematologi.list
    Hereditar_hypofystumorpanel:
      path: poirot/config/gene_panels/Hereditar_hypofystumorpanel.list
      checksum: 8c5864b94efa3e4447d56d97cb6779d8
      type: file
      url: file:poirot_config/config/gene_panels/Hereditar_hypofystumorpanel.list
    HHT_v1:
      path: poirot/config/gene_panels/HHT_v1.list
      checksum: 4a3a3551d783ddaa4b8b4f13ca03f003
      type: file
      url: file:poirot_config/config/gene_panels/HHT_v1.list
    Hjarnavvikelser_v1:
      path: poirot/config/gene_panels/Hjarnavvikelser_v1.list
      checksum: b981d462327badb3c50a89afd1a59abf
      type: file
      url: file:poirot_config/config/gene_panels/Hjarnavvikelser_v1.list
    Horsel:
      path: poirot/config/gene_panels/Horsel.list
      checksum: 2d44ba39b573faaa2148d9df5771f730
      type: file
      url: file:poirot_config/config/gene_panels/Horsel.list
    HSP_v2:
      path: poirot/config/gene_panels/HSP_v2.list
      checksum: babf34cc9426e65d08ed4179d95c8c51
      type: file
      url: file:poirot_config/config/gene_panels/HSP_v2.list
    Hyperinsulinism_hypoglycemi_v1:
      path: poirot/config/gene_panels/Hyperinsulinism_hypoglycemi_v1.list
      checksum: 22f8568de8f965402fd90cf46b622268
      type: file
      url: file:poirot_config/config/gene_panels/Hyperinsulinism_hypoglycemi_v1.list
    Hyperlipidemi_v1:
      path: poirot/config/gene_panels/Hyperlipidemi_v1.list
      checksum: a952c3e9e3789958f01585984a5742d2
      type: file
      url: file:poirot_config/config/gene_panels/Hyperlipidemi_v1.list
    Hyperparatyreoidism_v2:
      path: poirot/config/gene_panels/Hyperparatyreoidism_v2.list
      checksum: ccdd02cc86da336e39f4f147bee65ed2
      type: file
      url: file:poirot_config/config/gene_panels/Hyperparatyreoidism_v2.list
    Hypofystumor_v1:
      path: poirot/config/gene_panels/Hypofystumor_v1.list
      checksum: 8c5864b94efa3e4447d56d97cb6779d8
      type: file
      url: file:poirot_config/config/gene_panels/Hypofystumor_v1.list
    Hypogonadotrop_hypogonadism_v1:
      path: poirot/config/gene_panels/Hypogonadotrop_hypogonadism_v11.list
      checksum: 605e24ba29c688f4d31073248d7c2a51
      type: file
      url: file:poirot_config/config/gene_panels/Hypogonadotrop_hypogonadism_v1.list
    Hypoparatyreoidism_v2:
      path: poirot/config/gene_panels/Hypoparatyreoidism_v2.list
      checksum: 58f8011f904fe73c94d5267c4d353c1a
      type: file
      url: file:poirot_config/config/gene_panels/Hypoparatyreoidism_v2.list
    IF_v1:
      path: poirot/config/gene_panels/IF_v1.list
      checksum: 86d706dd3354dfee5da511570535f354
      type: file
      url: file:poirot_config/config/gene_panels/IF_v1.list
    Iktyos_v2:
      path: poirot/config/gene_panels/Iktyos_v2.list
      checksum: 5eb7b5dbe7be38ea5c1a48a291d8c763
      type: file
      url: file:poirot_config/config/gene_panels/Iktyos_v2.list
    Immun:
      path: poirot/config/gene_panels/Immun.list
      checksum: 6dc73df0db357250b6cd39df91ad8056 
      type: file
      url: file:poirot_config/config/gene_panels/Immun.list
    Intestinal_obstruktion_v1:
      path: poirot/config/gene_panels/Intestinal_obstruktion_v1.list
      checksum: 154093986e973ceeb6e834905cf64904 
      type: file
      url: file:poirot_config/config/gene_panels/Intestinal_obstruktion_v1.list
    Kardio:
      path: poirot/config/gene_panels/Kardio.list
      checksum: 761fdf007fee2f2f4b45b37f8ae81a3e
      type: file
      url: file:poirot_config/config/gene_panels/Kardio.list
    Kolestas_v1:
      path: poirot/config/gene_panels/Kolestas_v1.list
      checksum: 8ea784e8cc06cda537ed51564c1f2c34
      type: file
      url: file:poirot_config/config/gene_panels/Kolestas_v1.list
    Kortvuxenhet_v1:
      path: poirot/config/gene_panels/Kortvuxenhet_v1.list
      checksum: e79f5f67edc675500d281b8419c6cd2a
      type: file
      url: file:poirot_config/config/gene_panels/Kortvuxenhet_v1.list
    Kraniosynostos_v4:
      path: poirot/config/gene_panels/Kraniosynostos_v4.list
      checksum: 4b7b924e95e644d6bdfa3ada3d776715
      type: file
      url: file:poirot_config/config/gene_panels/Kraniosynostos_v4.list
    Meckel-Gruber_Joubert_v2:
      path: poirot/config/gene_panels/Meckel-Gruber_Joubert_v2.list
      checksum: 2dccfb5e65dde04ea9b5aa53eea6748a
      type: file
      url: file:poirot_config/config/gene_panels/Meckel-Gruber_Joubert_v2.list
    Mikrocefali_v1:
      path: poirot/config/gene_panels/Mikrocefali_v1.list
      checksum: 85caa60aad07274a75149ce910d13788
      type: file
      url: file:poirot_config/config/gene_panels/Mikrocefali_v1.list
    MODY_lipodystrophy:
      path: poirot/config/gene_panels/MODY_lipodystrophy.list 
      checksum: 27706e795da8f9b248d502736b0958c1
      type: file
      url: file:poirot_config/config/gene_panels/MODY_lipodystrophy.list       
    Multipla_kontrakturer_v1:
      path: poirot/config/gene_panels/Multipla_kontrakturer_v1.list
      checksum: 99e5c9f7ad16226c7c8320ba3ab97ea0
      type: file
      url: file:poirot_config/config/gene_panels/Multipla_kontrakturer_v1.list
    Neurodegenerativa_v1:
      path: poirot/config/gene_panels/Neurodegenerativa_v1.list
      checksum: 447be3edb03b98631b7a216495e1d00b
      type: file
      url: file:poirot_config/config/gene_panels/Neurodegenerativa_v1.list 
    Neuromuskular_v2:
      path: poirot/config/gene_panels/Neuromuskular_v2.list
      checksum: ee73dfc2bba83e52085e3564d5d30c43
      type: file
      url: file:poirot_config/config/gene_panels/Neuromuskular_v2.list
    Neuropati_v2:
      path: poirot/config/gene_panels/Neuropati_v2.list
      checksum: 77ede5990b214a2d224df5e0eefb9fe8 
      type: file
      url: file:poirot_config/config/gene_panels/Neuropati_v2.list
    Njurcancer:
      path: poirot/config/gene_panels/Njurcancer.list
      checksum: f4d06076f7cfda41f17e1bd176de251a
      type: file
      url: file:poirot_config/config/gene_panels/Njurcancer.list
    Njursjukdomar_v2:
      path: poirot/config/gene_panels/Njursjukdomar_v2.list
      checksum: f10e1b2ef5cf7b2b42a848f369088dd0
      type: file
      url: file:poirot_config/config/gene_panels/Njursjukdomar_v2.list
    Non-immune_hydrops_fetalis_v1:
      path: poirot/config/gene_panels/Non-immune_hydrops_fetalis_v1.list
      checksum: 897881935dfe3a2386758b80653f8c39
      type: file
      url: file:poirot_config/config/gene_panels/Non-immune_hydrops_fetalis_v1.list
    OI_och_benskorhet:
      path: poirot/config/gene_panels/OI_och_benskorhet.list
      checksum: ab14c93b0a63ad86e20f6b97f9e5541f
      type: file
      url: file:poirot_config/config/gene_panels/OI_och_benskorhet.list
    Obesitas_v2:
      path: poirot/config/gene_panels/Obesitas_v2.list
      checksum: 5d7058bdf80dd7ffb4578ba360ffb178
      type: file
      url: file:poirot_config/config/gene_panels/Obesitas_v2.list
    Okular_albinism:
      path: poirot/config/gene_panels/Okular_albinism.list
      checksum: 072ddd1d6977cdc3aa5cc9cae30ef006
      type: file
      url: file:poirot_config/config/gene_panels/Okular_albinism.list
    Optikus_atrofi:
      path: poirot/config/gene_panels/Optikus_atrofi.list
      checksum: 153c139f8fc723c5f1395302be36c3b4
      type: file
      url: file:poirot_config/config/gene_panels/Optikus_atrofi.list
    Pachyonychia_congenita:
      path: poirot/config/gene_panels/Pachyonychia_congenita.list
      checksum: 7f0da8676adfe4c00370eeab7fbc9af4
      type: file
      url: file:poirot_config/config/gene_panels/Pachyonychia_congenita.list
    PAH_v1:
      path: poirot/config/gene_panels/PAH_v1.list
      checksum: 49eb6d723ba1e6990997c7374f7090fc
      type: file
      url: file:poirot_config/config/gene_panels/PAH_v1.list
    Pankreatit_v1:
      path: poirot/config/gene_panels/Pankreatit_v1.list
      checksum: f1b1a6dd7e542a4a5f4edebdb90626d6
      type: file
      url: file:poirot_config/config/gene_panels/Pankreatit_v1.list
    Paragangliom_feokromocytom_v2:
      path: poirot/config/gene_panels/Paragangliom_feokromocytom_v2.list
      checksum: b35fa2ed4555dce717fea8644dce8af7
      type: file
      url: file:poirot_config/config/gene_panels/Paragangliom_feokromocytom_v2.list
    PCD_v2:
      path: poirot/config/gene_panels/PCD_v2.list
      checksum: b51aa61280720bd7d08e863525bf66bc
      type: file
      url: file:poirot_config/config/gene_panels/PCD_v2.list
    Periodisk_feber_v2:
      path: poirot/config/gene_panels/Periodisk_feber_v2.list
      checksum: 31c2b132faaa6145e983c3fe44272658
      type: file
      url: file:poirot_config/config/gene_panels/Periodisk_feber_v2.list
    Periodisk_paralys_v2:
      path: poirot/config/gene_panels/Periodisk_paralys_v2.list
      checksum: e9bb67a3ae386531ecd9f15d221d5a9b
      type: file
      url: file:poirot_config/config/gene_panels/Periodisk_paralys_v2.list
    Polycystisk_njursjukdom_v2:
      path: poirot/config/gene_panels/Polycystisk_njursjukdom_v2.list
      checksum: d9d791a65629fee8851f2f4f75639989
      type: file
      url: file:poirot_config/config/gene_panels/Polycystisk_njursjukdom_v2.list
    PPK_och_erytrodermi:
      path: poirot/config/gene_panels/PPK_och_erytrodermi.list
      checksum: 153826302957fda7068b3e826744403f
      type: file
      url: file:poirot_config/config/gene_panels/PPK_och_erytrodermi.list
    Primar_hyperaldosteronism_v1:
      path: poirot/config/gene_panels/Primar_hyperaldosteronism_v1.list
      checksum: 3240572128f2c0b7320357e06693abc6
      type: file
      url: file:poirot_config/config/gene_panels/Primar_hyperaldosteronism_v1.list
    Rasopatier:
      path: poirot/config/gene_panels/Rasopatier.list
      checksum: 9ed4634845e0c74a3b645af705e5c55f
      type: file
      url: file:poirot_config/config/gene_panels/Rasopatier.list
    Retinal_degeneration:
      path: poirot/config/gene_panels/Retinal_degeneration.list
      checksum: b195886c82fa59bbef972b1ef9578082
      type: file
      url: file:poirot_config/config/gene_panels/Retinal_degeneration.list
    Schwannomatos_och_menigiom:
      path: poirot/config/gene_panels/Schwannomatos_och_menigiom.list
      checksum: 7484e090dad9fc2a5e3ba0046a5d998a
      type: file
      url: file:poirot_config/config/gene_panels/Schwannomatos_och_menigiom.list
    Skelettdysplasi_v1:
      path: poirot/config/gene_panels/Skelettdysplasi_v1.list
      checksum: 813aff1dec8c64f2d9e984282de00f77
      type: file
      url: file:poirot_config/config/gene_panels/Skelettdysplasi_v1.list
    Sotos:
      path: poirot/config/gene_panels/Sotos.list
      checksum: d4abc6e1e442ee911cb672f6d5aafec3
      type: file
      url: file:poirot_config/config/gene_panels/Sotos.list
    Spermiedefekter_v1:
      path: poirot/config/gene_panels/Spermiedefekter_v1.list
      checksum: 396f4d3df4a8f35e1f4f753a4bf79e7c
      type: file
      url: file:poirot_config/config/gene_panels/Spermiedefekter_v1.list
    Trombocytopenier:
      path: poirot/config/gene_panels/Trombocytopenier.list
      checksum: 9f574a0896d2190f4382749091f5fe75
      type: file
      url: file:poirot_config/config/gene_panels/Trombocytopenier.list
    Tubulopati_v1:
      path: poirot/config/gene_panels/Tubulopati_v1.list
      checksum: 60420a38b046fde220b3832ee4d82cb8
      type: file
      url: file:poirot_config/config/gene_panels/Tubulopati_v1.list
    Tyroideahormonresistens_v2:
      path: poirot/config/gene_panels/Tyroideahormonresistens_v2.list
      checksum: e878e62de91bee6b831bdab7001c85a1
      type: file
      url: file:poirot_config/config/gene_panels/Tyroideahormonresistens_v2.list
    Wilms:
      path: poirot/config/gene_panels/Wilms.list
      checksum: 06f963c122cea8212f0449d2a33daba9
      type: file
      url: file:poirot_config/config/gene_panels/Wilms.list
