---

resources: "config/resources_production_pipeline.yaml"

reference:
  coverage_bed: "/beegfs-storage/data/ref_data/refseq/GCF_000001405.40-RS_2024_08_coverage_20260216.bed" 
  design_bed: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/homo_sapiens.hg38.wgs.bed"
  exome_bed: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/Twist_Comprehensive_Exome_Covered_Targets_hg38.bed"
  exome_intervals: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/Twist_Comprehensive_Exome_Covered_Targets_hg38.interval_list"
  fasta: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta"
  fai: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.fai"
  genepanels: "config/gene_panels/genepanels_WGS.list"
  sites: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/Homo_sapiens_assembly38.known_indels.vcf.gz"
  wgs_intervals: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/homo_sapiens.hg38.wgs.interval_list"
  str_panels_dir: "config/str_panels"
  str_panels:
    - "ataxi.list"
    - "dystoni.list"
    - "spastisk_paraplegi.list"
  merge_contigs: # contigs to be merged to a single BAM for mark duplicates
    - ".*_random"
    - "chrUn_.*"
    - "chrEBV"

bwa_mem:
  amb: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.amb"
  ann: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.ann"
  bwt: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.bwt"
  pac: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.pac"
  sa: "/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.sa"

bwa_mem_mito:
  amb:
    mt: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.amb"
    mt_shifted: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.amb"
  ann:
    mt: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.ann"
    mt_shifted: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.ann"
  bwt:
    mt: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.bwt"
    mt_shifted: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.bwt"
  pac:
    mt: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.pac"
    mt_shifted: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.pac"
  sa:
    mt: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.sa"
    mt_shifted: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.sa"

echtvar_anno:
  databases:
    - "/data/ref_data/wp3/nallo_refs/0.3.0/gnomad_snvs.zip"
    - "/data/ref_data/wp3/nallo_refs/0.3.0/CoLoRSdb.GRCh38.v1.2.0.deepvariant.glnexus.vcf.gz.zip"

expansionhunter:  
  variant_catalog: "config/str_catalog/variant_catalog_hg38.json"

filter_par_dups:
  bed: "config/cnv_filter_bed/chrX_PAR_HG38.bed"

gatk_lift_over_vcf:
  shift_back_chain: '/beegfs-storage/data/ref_data/gatk_mito/gatk_mito/ShiftBack.chain'

gatk_mutect2:
  interval:
    mt: "/beegfs-storage/data/ref_data/gatk_mito/non_control_region.chrM.interval_list"
    mt_shifted: "/beegfs-storage/data/ref_data/gatk_mito/control_region_shifted.chrM.interval_list"

glnexus_peddy:
  extra: "--bed /beegfs-storage/data/ref_data/peddy/v0.4.8/GRCH38.bed "

manta_config_n:
  extra: "--callRegions /beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GRCh38_chromosomes.bed.gz"

melt:
  container: "/projects/wp3/Software/MELTv2.2.2/MELT_v2.2.2.sif"
  bed: "/projects/wp3/Software/MELTv2.2.2/add_bed_files/Hg38/Hg38.genes.bed"
  mei: "/projects/wp3/Software/MELTv2.2.2/mei_list.txt"

mt_reference:
  mt: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta"
  mt_shifted: "/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta"
  blacklist: /beegfs-storage/data/ref_data/gatk_mito/blacklist_sites.hg38.chrM.bed

stranger:
  catalog: "config/str_catalog/variant_catalog_hg38.json"

svdb_query:
  db_string: "--db /beegfs-storage/data/ref_data/wp3/svdb/svdb_create_novaseqx/manta_wgs_hg38_novaseqX_v2.0.sorted.vcf.gz,/beegfs-storage/data/ref_data/wp3/svdb/svdb_create_novaseqx/cnvpytor_wgs_hg38_novaseqX_v2.1.sorted.vcf.gz,/beegfs-storage/data/ref_data/wp3/gnomad/gnomad.v4.1.sv.sites.no_cnv.PASS.vcf.gz"
  extra: "--in_frq FRQ,FRQ,AF --in_occ OCC,OCC,AC --out_frq manta_FRQ,cnvpytor_FRQ,gnomad_AF --out_occ manta_OCC,cnvpytor_OCC,gnomad_AC "

vep:
  vep_cache: "/beegfs-storage/data/ref_genomes/VEP/"

vep_svdb:
  vep_cache: "/beegfs-storage/data/ref_genomes/VEP/"

verifybamid2:
  svd_mu: "/beegfs-storage/data/ref_data/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.mu"

